### Get all tasks
# GET http://localhost:5000/tasks

# ## Add a new task
# POST http://localhost:5000/tasks
# Content-Type: application/json

# {
#   "title": "Practice Aptitude"
# }

### Get all tasks
# GET http://localhost:5000/tasks

### Update a task
# PUT http://localhost:5000/tasks/67d401ab11cd4c668ae1d7d8
# Content-Type: application/json

# {
#   "completed": true
# }

# ### Get all tasks
# GET http://localhost:5000/tasks

# ### Delete a task
# DELETE http://localhost:5000/tasks/3

# ### Get all tasks
# GET http://localhost:5000/tasks


### Test Google OAuth Login/Signup (This will redirect to Google)
GET http://localhost:5000/auth/google


### Local Signup
POST http://localhost:5000/auth/signup
Content-Type: application/json

{
    "email": "test@example.com",
    "password": "password123",
    "name": "Test User"
}

### Local Login
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email": "jagadeeshjagan2003@gmail.com",
    "password": "1234"
}

### Logout
GET http://localhost:5000/auth/logout

### Get Current User Profile
GET http://localhost:5000/auth/profile